import random

class Column:
    def __init__(self, name, type) -> None:
        self.name = name
        self.type = type
        assert type in [str, int]

        self.varchar_length = 2
        self.generated = (self.name  == "id")

    def sql(self):
        if self.generated:
            return f"{self.name} INTEGER generated by default as identity primary key"
        elif self.type == str:
            return f"{self.name} VARCHAR({self.varchar_length})"   
        elif self.type == int:
            return f"{self.name} INTEGER"
        else:
            raise Exception("Unknown")   

    def generate(self):
        if self.type == str:
            words = "".join([
                chr(random.randint(65, 65 + 20)) for i in range(self.varchar_length - 1)
            ])
            return f"'{words}'"
        else:
            return random.randint(100, 1000)
        